name: build yys-tool

on:
  push:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
permissions:
  contents: read
  pages: write # to deploy to Pages
  id-token: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: npm_run_build
        run: |
          npm i && npm run build

      - name: upload files
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-dist
          path: dist
          retention-days: 1

  Deploy:
    needs: Build
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build-dist
